name: laravel

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
    volumes:
      - storage-public:/var/www/html/storage/app/public
    networks:
      - laravel-network
      - proxy-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-worker
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    environment:
      APP_ENV: production
    volumes:
      - storage-public:/var/www/html/storage/app/public
    networks:
      - laravel-network
      - proxy-network
    depends_on:
      - app

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    container_name: laravel-webserver
    restart: unless-stopped
    volumes:
      - storage-public:/var/www/html/storage/app/public:ro
    networks:
      - laravel-network
      - proxy-network
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`jfxtech.com.br`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

networks:
  laravel-network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  storage-public:
